# Generated by Django 4.0.5 on 2022-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=6)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
